.global PRIMITIVE_WORD_BITMASK

.equ UART_BASE2, 0x40004400
.equ CELL_SIZE, 4
.equ SHORT_SIZE, 2
.equ DATA_STACK_MAX_SIZE, 32
.equ RETURN_STACK_MAX_SIZE, 64

.equ HEADER_NAME_BUF_SIZE, 32
.equ HEADER_CODE_BUF_SIZE, 32

.equ DATA_STACK_MAX_SIZE_BYTES, (DATA_STACK_MAX_SIZE * CELL_SIZE)


.equ TOKEN_BUFFER_MAX_SIZE, 32
.equ LINE_BUFFER_MAX_SIZE, 128
.altmacro

.data

# flags

.equ COMPILE_BIT, 1
.equ COMMENT_BIT, 2
.equ FIND_TOKEN_ERROR_BIT, 4
.equ NUM_IO_HEX_BIT, 8   # if not set, num io is decimal

.extern RAM_START, 0x20000000

.equ PRIMITIVE_WORD_BITMASK, 2

.macro StackSizeElements regSize, regTemp, regOut
    li \regTemp, CELL_SIZE
    div \regOut, \regSize, \regTemp 
.endm


.macro PushStack regBase, regSize, regVal
    add t0, \regBase, \regSize
    sw \regVal, 0(t0)
    addi \regSize, \regSize, CELL_SIZE
.endm

.macro PopStack regBase, regSize, regOutVal
    addi \regSize, \regSize, -CELL_SIZE
    add t0, \regBase, \regSize
    lw \regOutVal, 0(t0)
.endm
#     s0 - instruction pointer
#     s1 - data stack base pointer
#     s2 - data stack size
#     s3 - return stack base pointer
#     s4 - return stack size
#     s5 - memory top

.macro PushDataStack regVal
    PushStack s1, s2, \regVal
.endm

.macro PopDataStack regOutVal
    PopStack s1, s2, \regOutVal
.endm

.macro PushReturnStack regVal
    PushStack s3, s4, \regVal
.endm

.macro PopReturnStack regOutVal
    PopStack s3, s4, \regOutVal
.endm

.macro padded_string string, max
1:
    .ascii \string
2:
    .iflt \max - (2b - 1b)
    .error "String too long"
    .endif

    .ifgt \max - (2b - 1b)
    .zero \max - (2b - 1b)
    .endif

.endm

# Imaginary C Struct - word header
#
# struct Header
# {
#     char code[HEADER_CODE_BUF_SIZE];       // the code you write when you write forth 
#     struct Header* next;
#     struct Header* prev;
#     Cell bflags;
# }

.macro word_header_unitialised name, code, flags
    .balign 4
\name:
    #padded_string \code, HEADER_CODE_BUF_SIZE
1:
    .ascii \code
2:
    .iflt HEADER_CODE_BUF_SIZE - (2b - 1b)
    .error "String too long"
    .endif

    .ifgt HEADER_CODE_BUF_SIZE - (2b - 1b)
    .zero HEADER_CODE_BUF_SIZE - (2b - 1b)
    .endif
    .word 0
    .word \flags
\name\()_impl:
.endm

.macro word_header_last name, code, flags, prev
    .balign 4
\name:
    padded_string \code, HEADER_CODE_BUF_SIZE
    .word \prev
    .word \flags
\name\()_impl:
.endm


.macro word_header_first name, code, flags, next
    .balign 4
\name:
    padded_string \code, HEADER_CODE_BUF_SIZE
    .word 0
    .word \flags
\name\()_impl:
.endm

.macro word_header name, code, flags, next, prev
    .balign 4
\name:
    #padded_string \code, HEADER_CODE_BUF_SIZE
1:
    .ascii \code
2:
    .iflt HEADER_CODE_BUF_SIZE - (2b - 1b)
    .error "String too long"
    .endif

    .ifgt HEADER_CODE_BUF_SIZE - (2b - 1b)
    .zero HEADER_CODE_BUF_SIZE - (2b - 1b)
    .endif
    .word \prev
    .word \flags
\name\()_impl:
.endm

.macro decode_half_word_ptr \inHalfWordPtrReg, \outRawPtrReg
    andi t0, \inHalfWordPtrReg, 1
    beq t0, zero, 1f
    # first bit is set, therefore this is an offset into the RAM
    li t0, RAM_START
    add \inHalfWordPtrReg, t0, \inHalfWordPtrReg
    # reset 1 bit
    li t0, ~1
    and \inHalfWordPtrReg, \inHalfWordPtrReg, t0
1:
    mv \outRawPtrReg, \inHalfWordPtrReg

.endm


.macro secondary_word name
    PushReturnStack s0
    la s0, \name\()_ThreadBegin
    lh t4, 0(s0)
    decode_half_word_ptr t4, t5
    # DEBUG TRACE CODE BEGIN
    # mv a0, t4
    # call print_int
    # la a0, linened2
    # li a1, UART_BASE2
    # call puts
    # DEBUG TRACE CODE END
    jalr ra, t5, 0
    .balign 4
\name\()_ThreadBegin:
.endm

.equ OFFSET_CODE, 0
.equ OFFSET_PREV, (HEADER_CODE_BUF_SIZE)
.equ OFFSET_IMM, (OFFSET_PREV + CELL_SIZE)
.equ HEADER_SIZE, OFFSET_IMM + CELL_SIZE

.macro word_next regPtrHeader, regPtrOut
    addi \regPtrOut, \regPtrHeader, OFFSET_NEXT
.endm

.macro word_prev regPtrHeader, regPtrOut
    addi \regPtrOut, \regPtrHeader, OFFSET_PREV
.endm

.macro word_imm regPtrHeader, regPtrOut
    addi \regPtrOut, \regPtrHeader, OFFSET_IMM
.endm

.macro word_code regPtrHeader, regPtrOut
    addi \regPtrOut, \regPtrHeader, OFFSET_CODE
.endm


.macro end_word
    addi s0, s0, SHORT_SIZE

    lh t4, 0(s0)
    decode_half_word_ptr t4, t5
    # DEBUG TRACE CODE BEGIN
    # mv a0, t4
    # call print_int
    # la a0, linened2
    # li a1, UART_BASE2
    # call puts
    # DEBUG TRACE CODE END
    jalr ra, t5, 0
.endm

# Following 2 macros used to calculate branch labels within pre-compiled secondary words
.macro CalcBranchBackToLabel label
    # ASSUMES THAT 1b IS A LABEL TO THE BRANCH OR BRANCHZERO IMPLEMENTATION POINTER
    .word - (( 1b - \label ) + 1 * CELL_SIZE)
.endm

.macro CalcBranchForwardToLabel label
    # ASSUMES THAT 1b IS A LABEL TO THE BRANCH OR BRANCHZERO IMPLEMENTATION POINTER
    .word (( \label - 1b) - 1 * CELL_SIZE)
.endm

.text
linened2: .ascii "\n\r\0"

.balign 4


#
# Optimized for space:
# instead of word sized raw pointers we write 16 bit offsets.
# These are word aligned and so the bottom bit signifies whether an offset
# to the RAM region or not
#
.macro impl_ptr ptr
    .if \ptr >= RAM_START
        .hword ((\ptr - RAM_START) | 1)  & 0xffff
    .else
        .hword \ptr & 0xffff
    .endif
.endm
